### ISSUE TITLE
Connection reset error

### ISSUE THREAD

**Issue by Swader** [AuroraDAO/aurad#5]
I started getting intermittent connection reset errors now, too. Does not seem to permanently break staking, though staking is [arguably broken](#3) at the moment anyway.

```
11:41:53 0|worker  |     at Request.plumbing.callback (/usr/aurad/node_modules/request-promise-core/lib/plumbing.js:87:29)
11:41:53 0|worker  |     at Request.RP$callback [as _callback] (/usr/aurad/node_modules/request-promise-core/lib/plumbing.js:46:31)
11:41:53 0|worker  |     at self.callback (/usr/aurad/node_modules/request/request.js:185:22)
11:41:53 0|worker  |     at Request.emit (events.js:182:13)
11:41:53 0|worker  |     at Request.onRequestError (/usr/aurad/node_modules/request/request.js:881:8)
11:41:53 0|worker  |     at ClientRequest.emit (events.js:182:13)
11:41:53 0|worker  |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
11:41:53 0|worker  |     at TLSSocket.emit (events.js:182:13)
11:41:53 0|worker  |     at emitErrorNT (internal/streams/destroy.js:82:8)
11:41:53 0|worker  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
11:41:53 0|worker  |     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
11:41:53 0|worker  |     at process._tickCallback (internal/process/next_tick.js:63:19)
11:41:53 0|worker  |   name: 'RequestError',
11:41:53 0|worker  |   message: 'Error: read ECONNRESET',
11:41:53 0|worker  |   cause:
11:41:53 0|worker  |    { Error: read ECONNRESET
11:41:53 0|worker  |        at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
11:41:53 0|worker  |   error:
11:41:53 0|worker  |    { Error: read ECONNRESET
11:41:53 0|worker  |        at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
11:41:53 0|worker  |   options:
11:41:53 0|worker  |    { url: 'https://sc.idex.market/keepalive',
11:41:53 0|worker  |      method: 'POST',
11:41:53 0|worker  |      headers:
11:41:53 0|worker  |       { 'x-aurad-id': '0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F',
11:41:53 0|worker  |         'x-aurad-address': '0x06b9B6C65a519EF18b7e364E2A6D22e5cA707a14',
11:41:53 0|worker  |         'x-aurad-date': 1547466113490,
11:41:53 0|worker  |         'x-aurad-digest':
11:41:53 0|worker  |          '6f6671a2f8fe33c3c1a00b6d150abf19205cd79361af9ce7f89335dff887dea8',
11:41:53 0|worker  |         'x-aurad-authorization':
11:41:53 0|worker  |          '0x1abd3d7b09cfa4121e555487c408c79264ed307ebbc331421d2c6785c00bea0b68c09905f4db235c09a18b475ca65a45668871afb181bdf9a6b575bd5167596f1c',
11:41:53 0|worker  |         'x-aurad-challenge': undefined },
11:41:53 0|worker  |      json:
11:41:53 0|worker  |       { version: '0.1.0',
11:41:53 0|worker  |         blockNumber: 7064556,
11:41:53 0|worker  |         timestamp: 1547466113490 },
11:41:53 0|worker  |      simple: false,
11:41:53 0|worker  |      resolveWithFullResponse: true,
11:41:53 0|worker  |      callback: [Function: RP$callback],
11:41:53 0|worker  |      transform: undefined,
11:41:53 0|worker  |      transform2xxOnly: false },
11:41:53 0|worker  |   response: undefined }
```

**Comment by yennieb** [comment]
@Swader it's hard to tell from this trace, but it looks like you were having connection errors with the staking coordinator. This could be on our end or yours, but we need roll out a couple of stability updates in the past couple days. Please let us know if you continue to get the errors.

**Comment by Swader** [comment]
Much rarer, but saw one around 12:02 GMT today:

```
12:02:19 0|worker  |     at new RequestError (/usr/aurad/node_modules/request-promise-core/lib/errors.js:14:15)
12:02:19 0|worker  |     at Request.plumbing.callback (/usr/aurad/node_modules/request-promise-core/lib/plumbing.js:87:29)
12:02:19 0|worker  |     at Request.RP$callback [as _callback] (/usr/aurad/node_modules/request-promise-core/lib/plumbing.js:46:31)
12:02:19 0|worker  |     at self.callback (/usr/aurad/node_modules/request/request.js:185:22)
12:02:19 0|worker  |     at Request.emit (events.js:182:13)
12:02:19 0|worker  |     at Request.onRequestError (/usr/aurad/node_modules/request/request.js:881:8)
12:02:19 0|worker  |     at ClientRequest.emit (events.js:182:13)
12:02:19 0|worker  |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
12:02:19 0|worker  |     at TLSSocket.emit (events.js:182:13)
12:02:19 0|worker  |     at emitErrorNT (internal/streams/destroy.js:82:8)
12:02:19 0|worker  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
12:02:19 0|worker  |     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
12:02:19 0|worker  |     at process._tickCallback (internal/process/next_tick.js:63:19)
12:02:19 0|worker  |   name: 'RequestError',
12:02:19 0|worker  |   message: 'Error: read ECONNRESET',
12:02:19 0|worker  |   cause:
12:02:19 0|worker  |    { Error: read ECONNRESET
12:02:19 0|worker  |        at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
12:02:19 0|worker  |   error:
12:02:19 0|worker  |    { Error: read ECONNRESET
12:02:19 0|worker  |        at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
12:02:19 0|worker  |   options:
12:02:19 0|worker  |    { url: 'https://sc.idex.market/keepalive',
12:02:19 0|worker  |      method: 'POST',
12:02:19 0|worker  |      headers:
12:02:19 0|worker  |       { 'x-aurad-id': '0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F',
12:02:19 0|worker  |         'x-aurad-address': '0x06b9B6C65a519EF18b7e364E2A6D22e5cA707a14',
12:02:19 0|worker  |         'x-aurad-date': 1547812939214,
12:02:19 0|worker  |         'x-aurad-digest':
12:02:19 0|worker  |          '2ad18ebf783fb3b6cebb7cf18bc12a094f4fae95ecb2040cedc3cf132baffec9',
12:02:19 0|worker  |         'x-aurad-authorization':
12:02:19 0|worker  |          '0xff16e6c0961d0ac0f7171f6ec2d93bdfebcb5bd4fe399e70f7d08a071bc0d2fd689087f832beb585e109ccea6893be82e4533af53530b2a9611cb06f8d3b1d5b1c',
12:02:19 0|worker  |         'x-aurad-challenge': undefined },
12:02:19 0|worker  |      json:
12:02:19 0|worker  |       { version: '0.1.0',
12:02:19 0|worker  |         blockNumber: 7087022,
12:02:19 0|worker  |         timestamp: 1547812939214 },
12:02:19 0|worker  |      simple: false,
12:02:19 0|worker  |      resolveWithFullResponse: true,
12:02:19 0|worker  |      callback: [Function: RP$callback],
12:02:19 0|worker  |      transform: undefined,
12:02:19 0|worker  |      transform2xxOnly: false },
12:02:19 0|worker  |   response: undefined }
12:02:43 0|worker  | Processing blocks 7087023 to 7087025
12:02:47 0|worker  | Waiting for new blocks @fter 7087025
12:02:49 0|worker  | STAKING ONLINE: In rotation
12:03:19 0|worker  | STAKING ONLINE: In rotation
```
