### ISSUE TITLE
Also getting 2 errors tho they are rare.  

### ISSUE THREAD

**Issue by shirec** [AuroraDAO/aurad#6]
Currently running this on Oracle VM/ Ubuntu 64 bit and a PC that well and truly exceeds specs on a 100/40 connection with unlimited data and hard wired connection. Just thought this might help. Let me know if you need me to do anything happy to help out. Cheers.

First one though it could be hours or even days apart. It could be my network suffering a very minor and short issue. Not sure. 
```
23:52:00 0|worker  | STAKING ONLINE: In rotation
23:52:17 0|worker  | Processing blocks 7061815 to 7061816
23:52:18 0|worker  | Waiting for new blocks @fter 7061816
23:52:31 0|worker  | STAKING OFFLINE: Your health check failed or timed out. Try again in a minute and make sure that your computer is publicly accessible at https://0xed1e282b833232d32ade4769985f5a7a5959f8ee.tier3.aurastaking.net:8443/health
23:52:37 0|worker  | Processing blocks 7061817 to 7061818
23:52:38 0|worker  | Waiting for new blocks @fter 7061818
23:53:01 0|worker  | STAKING ONLINE: In rotation
23:53:25 0|worker  | Processing blocks 7061819 to 7061820
```
Second block of issues tho this is also fairly rare and you can see it fixes itself in 30 seconds. 
```
18:27:29 0|worker  | STAKING ONLINE: In rotation
18:27:49 0|worker  | Processing blocks 7060502 to 7060503
18:27:50 0|worker  | Error: receipt is null
18:27:50 0|worker  |     at Object.cb [as callback] (/usr/aurad/lib/worker.js:277:31)
18:27:50 0|worker  |     at /usr/aurad/node_modules/web3-core-requestmanager/src/batch.js:65:37
18:27:50 0|worker  |     at Array.forEach (<anonymous>)
18:27:50 0|worker  |     at /usr/aurad/node_modules/web3-core-requestmanager/src/batch.js:54:12
18:27:50 0|worker  |     at /usr/aurad/node_modules/web3-core-requestmanager/src/index.js:173:9
18:27:50 0|worker  |     at XMLHttpRequest.request.onreadystatechange (/usr/aurad/node_modules/web3-providers-http/src/index.js:96:13)
18:27:50 0|worker  |     at XMLHttpRequestEventTarget.dispatchEvent (/usr/aurad/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
18:27:50 0|worker  |     at XMLHttpRequest._setReadyState (/usr/aurad/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
18:27:50 0|worker  |     at XMLHttpRequest._onHttpResponseEnd (/usr/aurad/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
18:27:50 0|worker  |     at IncomingMessage.<anonymous> (/usr/aurad/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
18:27:50 0|worker  |     at IncomingMessage.emit (events.js:187:15)
18:27:50 0|worker  |     at endReadableNT (_stream_readable.js:1094:12)
18:27:50 0|worker  |     at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
18:27:50 0|worker  |     at process._tickCallback (internal/process/next_tick.js:63:19)
18:27:50 0|worker  | Error processing transactions, retry in 5 seconds
18:27:55 0|worker  | Processing blocks 7060502 to 7060503
18:27:56 0|worker  | Waiting for new blocks @fter 7060503
18:27:59 0|worker  | STAKING ONLINE: In rotation
```

**Comment by yennieb** [comment]
@shirec can you confirm you are using the default parity RPC client when you get this `receipt is null` error?

**Comment by shirec** [comment]
I am using the Infura RPC endpoint. If I used the default I get the RPC time out issues others have had.

**Comment by shirec** [comment]
Getting the above errors still and now also getting the staking offline message every so often. As is everyone else I believe.

**Comment by Bobface** [comment]
I am also getting the same error (receipt is null) using Infura.

**Comment by shirec** [comment]
After the update I am still getting the second set of errors come up. Twice in 2 hours now. The other issue tho seems to be a lot better now.

**Comment by shirec** [comment]
Another update.... Still getting the second error message tho my offline to online ration is  1/3361. If I can sort this error out It would almost be 100 percent.

**Comment by shirec** [comment]
STILL GETTING THEM.
